prueba/todolistapp/config/routes.rb
Rails.application.routes.draw do

  get 'completados/create'
  get 'tarea/index'
  resources :tareas do
    resources :completados, only: [:create, :update, :show]
  end
  resources :completados, only: :index
  root to: 'tareas#index'
  devise_for :usuarios
end

prueba/todolistapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

prueba/todolistapp/app/models/completado.rb
class Completado < ApplicationRecord
  belongs_to :usuario
  belongs_to :tarea
end

prueba/todolistapp/app/models/tarea.rb
class Tarea < ApplicationRecord

    has_many :completados
    has_many :usuarios, through: :completados
end

prueba/todolistapp/app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :completados
  has_many :tareas, through: :completados
end

prueba/todolistapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

prueba/todolistapp/app/controllers/completados_controller.rb
class CompletadosController < ApplicationController
  before_action :authenticate_usuario!

  def create
    @tarea = Tarea.find(params[:tarea_id])
    @usuario = current_usuario
    @existe =  Completado.where(tarea: @tarea, usuario: current_usuario)
    if @existe.empty?
      @creado = Completado.new(tarea: @tarea, usuario: current_usuario, listo: true)
      if @creado.save
          redirect_to tareas_path, notice: 'La tarea ha sido completada'
        else
          redirect_to tareas_path, alert: 'La tarea no ha podido ser completada'
      end
    else
  		if Completado.where(tarea: @tarea, usuario: current_usuario).update(listo: true)
  			redirect_to root_path, notice:'La tarea ha sido completada'
  		  else
  			redirect_to root_path, alert:"La tarea no ha podido ser completada"	
  		end
	  end	
  end

  def update
  	@tarea = Tarea.find(params[:tarea_id])
  	@usuario = current_usuario
  	if Completado.where(tarea: @tarea, usuario: current_usuario).update(listo: false)
  		redirect_to root_path, notice:'La tarea ha sido desmarcada'
  	else
  		redirect_to root_path, alert:"La tarea NO ha sido desmarcada"	
  	end
  end

  def completado_params
  	params.require(:completado).permit(:usuario_id, :tarea_id, :listo)
  end
end

prueba/todolistapp/app/controllers/tareas_controller.rb
class TareasController < ApplicationController

  def index
    @listo = []
    @tarea = Tarea.all
   if usuario_signed_in?
        @completado = Completado.select(:usuario_id, :tarea_id).where(:usuario_id => current_usuario, :listo => true).all
        @completado.each do |lista|
        @listo << lista.tarea_id 
    end
        @completos = @listo.length
        @total = Tarea.all.count
  end
 end

 def show
  @listo= []
  @usuarios = []
  @tarea= Tarea.find(params[:id])
   if usuario_signed_in?  
        @usuarios = Usuario.joins(:completados).where(completados: {tarea_id: @tarea, listo: true})
        @completado = Completado.select(:usuario_id, :tarea_id).where(:usuario_id => current_usuario, :listo => true).all
        @completado.each do |l|
        @listo << l.tarea_id 
     end
        @completos = @listo.length
        @total = Tarea.all.count
        @ranking = Usuario.joins(:completados).where(completados: {tarea_id: @tarea, listo: true}).order('updated_at').limit(5)
   end
 end

 def tareas_params
     params.require(:tarea).permit(:name, :description, :photo)
 end
end

prueba/todolistapp/app/helpers/application_helper.rb
module ApplicationHelper
end

prueba/todolistapp/app/helpers/completados_helper.rb
module CompletadosHelper
end

prueba/todolistapp/app/helpers/tareas_helper.rb
module TareasHelper
end

prueba/todolistapp/app/views/completados/create.html.erb
<h1>Completados#create</h1>
<p>Find me in app/views/completados/create.html.erb</p>

prueba/todolistapp/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href=" <%root_path%>">TodoList</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <% if usuario_signed_in? %>
        <li><a href=" <%root_path%> ">Tareas completadas: <span class="sr-only">(current)</span></a></li>
        <li><a href="#"> <%= @completos %> </a></li>
       <% else %>
        <li><a href="#">Inicia sesion para completar tareas!!! <span class="sr-only">(current)</span></a></li>
      <% end %> 
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if usuario_signed_in? %>
          <li> <a> <%= current_usuario.email %> </a></li>
          <button type="submit" class="btn btn-default navbar-btn"> <%= link_to('Cerrar Sesión', destroy_usuario_session_path, method: :delete) %></button>
        <% else %>
          <button type="submit" class="btn btn-default navbar-btn"> <%= link_to('Iniciar Sesión', new_usuario_session_path) %> </button>
          <button type="submit" class="btn btn-default navbar-btn"> <%= link_to('Crear Cuenta', new_usuario_registration_path) %></button>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

prueba/todolistapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolistapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <% if notice.present?%>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% end%>

    <% if alert.present?%>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
      </div>
    <% end%>

    <%= yield %>
  </body>
</html>

prueba/todolistapp/app/views/tareas/index.html.erb
<div class = "container">
    <h1>VIVA EL 18!!!</h1>
    <h2>Intenta completar todas estas Tareas este 18 de SeDtiembre!!!!</h2>

    <div class ="row">
        <% @tarea.each do |tarea| %>
            <div class="col-md-4">
                <div class = "card">
                    <%= image_tag tarea.photo, size: '300x200',class: "card-img-top" %>
                <div class = "body">
                    <h4><%=tarea.name%></h4>
                    <p><%=tarea.description%> </p>
                    <% if @listo.include?(tarea.id) %>
                        <%=link_to "Desmarcar", tarea_completado_path(tarea,current_usuario), class: 'btn btn-danger', method: :put %>
                    <% else %>
                        <%=link_to "completar", tarea_completados_path(tarea), class: 'btn btn-primary', method: :post %>
                    <% end %>
                    <%=link_to "Detalle", tarea_path(tarea), class: 'btn btn-primary' %>
                    </div>
                </div>
            <div class ="w-100" style="margin-top:20px"></div>
            </div>
        <% end %>
    </div>
</div>

prueba/todolistapp/app/views/tareas/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-5">
			<h1> Los Primeros 5</h1>
			<% @ranking.each do |lista| %> 
				<h2><%=lista.email %> <%=lista.updated_at %></h2>
			<% end %>
		</div>
		<div class="col-md-3">
			<h3>Todos los usuarios que la han completado</h3>
			<% @usuarios.each do |user| %>
			<p><%= user.email %></p>
			<% end %>
		</div>
		<div class="col-md-4">
			<h3> <%= @tarea.name %> </h3>	
			<p> <%= @tarea.description %> </p>
			<%= image_tag("#{@tarea.photo}", size: '300x200') %>
			<%= link_to 'volver', root_path, :class => 'btn btn-success' %>
		</div>
	</div>
	
</div>